apiVersion: v1
kind: LimitRange
metadata:
  name: go-web-app-limits
  namespace: go-launch-app # Ensure this matches your deployment's namespace
spec:
  limits:
    - default:
        cpu: "500m"
        memory: "512Mi"
      defaultRequest:
        cpu: "250m"
        memory: "256Mi"
      max:
        cpu: "1"
        memory: "1Gi"
      min:
        cpu: "100m"
        memory: "64Mi"
      type: Container
